### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by asolino** [SecureAuthCorp/impacket#61]
We should add Python3 support for the library. Ideally, the same codebase should run on both versions. 

I've just created a [python3 branch](https://github.com/CoreSecurity/impacket/tree/python3) to work on porting the existing code. 

[structure.py](https://github.com/CoreSecurity/impacket/blob/python3/impacket/structure.py), which is a core component for the library, seems to be working on Python3 now.  A lot of testing is needed tho. 

PRs welcomed!

**Comment by kupiakos** [comment]
I'm considering working on this and taking advantage of the [six](https://pypi.python.org/pypi/six) library to make porting simpler with a single Python source. Is there any additional progress people should know about?

**Comment by asolino** [comment]
Hey there. 
[six](https://pypi.python.org/pypi/six) will surely help you. I'd suggest tho to go slowly. Impacket relies heavily on the str object (sadly) and that is one of the biggest changes in Python3. 
That's the reason why I started porting [structure.py](https://github.com/CoreSecurity/impacket/blob/python3/impacket/structure.py) first since it is heavily used. 
If you want to get into the DCE-RPC side, [ndr.py](https://github.com/CoreSecurity/impacket/blob/python3/impacket/dcerpc/v5/ndr.py), which is the NDR runtime, is another critical part of the library.

Finally, this branch is out-dated, so first off I'd try to update it with the latests changes from master.

Thanks for taking a crack at this!

**Comment by bharel** [comment]
What's the status regarding the porting? This issue and the Python 3 branch seem quite outdated. Was the porting abandoned? Do you guys need help with it?

**Comment by asolino** [comment]
hey @bharel 

Yup, that branch is quite outdated. Didn't have time much time to keep working on it. In fact, it was more of a first crack at Python3 than a serious project. 
You're very welcomed to help on it if you have Python 3 experience (I don't have much).

**Comment by crutchcorn** [comment]
I'd love to be able to help, especially as a work project I have will share some of the codebase. Is there anyone that has more up to date work on this? If so, please link me so that I can start working on it. Otherwise - expect a fork and PR whenever I get a spare moment

**Comment by euri10** [comment]
I begun doing some work on that daunting task :)

I pushed several things here https://github.com/euri10/impacket/tree/py3

With such a task I thought it would be easier and more consistent to try to test things with the help of tox.

So I created a tox.ini that only tests 2.7 for the moment, but once that will be running ok, it will be a matter of adding 4 characters, to tests on the same basis python 3, better to be on the safe side.

For that I made some changes: 

1. the testcases folder has been upped one level and all subsequents imports have been adapted
2. nose is used for test discovery and so far xxx tests are processed, all dot11 tests run ok, all but one ImpactPacket toom and most SMB_RPC fail

Some fails are due to my config I presume, I'm no windows pro :) and some are normal to fail if I read correctly the comments at the top of each test file.

In order to push the test completion a little further and before attempting to write changes for python 3 I therefore have a few questions:

About the tests that fail due to my windows 10 VM config:

- I'm missing in the dcetests.cfg file several entries, I don't know what to fill in here: hashes = , aesKey256 =  and aesKey128 = 
- I see those errors quite often in several tests, is it a misconfiguration on my side, some tweaks I should do on my windows VM ?

DCERPCException: rpc_s_access_denied
DCERPCException: DCERPC Runtime Error: code: 0x16c9a0d6 - ept_s_not_registered
DCERPCException: Bind context 1 rejected: provider_rejection; abstract_syntax_not_supported (this usually means the interface isn't listening on the given endpoint)
NetBIOSTimeout: The NETBIOS connection with the remote host timed out.
DCERPCException: Bind context 1 rejected: provider_rejection; abstract_syntax_not_supported (this usually means the interface isn't listening on the given endpoint)

- I also have lots of error like the following AttributeError: 'DCOMTests' object has no attribute 'stringBinding' and I guess for those ones, it's more my issue of having moved things around and the test case not loading up the various tests correctly

- I have an issue with DCERPCException: Could not connect: timed out in SMB_RPC/test_samr.py the result being the TCPTransport test takes 30+ minutes to run because of the 30s timeout that is reached every single time, I'd like to solve this one first :)

Happy to hear your thoughts

**Comment by wrb233** [comment]
希望能尽快支持python3

**Comment by robertpro** [comment]
How is this going ? I can not find the python3 branch

**Comment by infinnovation-dev** [comment]
I see there is a [python36](https://github.com/SecureAuthCorp/impacket/tree/python36) branch with some activity (e.g. merging in changes to master).  Note that impacket is being used in the curl project for regression testing - see curl/curl#3289

**Comment by asolino** [comment]
Hey @infinnovation-dev 

Indeed it has some activity (107 commits ahead of master as of today). I heavily worked on that during September and October. 
I will be merging it to master once I fix some remaining test cases that are still failing. 
But there must be more things to test, so please let us know if you find something not working.

**Comment by cclauss** [comment]
@asolino Can you please provide an update on your efforts?  There are now < 350 days until Python 2 end of life and several downstream projects need to start their porting efforts to avoid a last minute rush.  https://github.com/SecureAuthCorp/impacket/tree/python36 is now almost 200 commits ahead of master.

**Comment by asolino** [comment]
python36 branch is still under testing @cclauss. If anybody want to start their porting efforts they can use that branch and file any issues they face. I'm using it pretty often and so far so good.

>  https://github.com/SecureAuthCorp/impacket/tree/python36 is now almost 200 commits ahead of master.

Right now we're at 200 commits ahead sharp,  thanks for pointing that out! Very useful.

**Comment by kloczek** [comment]
I've been trying to use Fedora python3 patch but many tests are failing on python synta issues
https://github.com/curl/curl/issues/3622

**Comment by xambroz** [comment]
I just learned the package python-impacket was removed from Fedora head due to lack of python3 support (by Miro Hroncok).
https://src.fedoraproject.org/rpms/python-impacket/tree/master
https://src.fedoraproject.org/rpms/python-impacket/c/3cdb1dd4b08e63f427d10a16a7bb786c17008a64?branch=master

**Comment by cclauss** [comment]
Can we close this issue?  README.md says that Python 3.6 is supported.

**Comment by asolino** [comment]
Yes, closing this issue since we're supporting Python 3.6.x in master branch.

**Comment by hroncok** [comment]
@xambroz the package was re-added to Fedora - would you might updating it Python 3?

**Comment by Iansus** [comment]
Branch 3.7.x is not supported, many lines fail due to old Python 2.7.x syntax.
For example:

```
    from impacket import nt_errors, version, smb
  File "C:\xxxx\tests\lib\site-packages\impacket\smb.py", line 637
    y = t & 0xffffffffL
                      ^
SyntaxError: invalid syntax
```

**Comment by Iansus** [comment]
(And the same error arises in 3.5.x)

**Comment by asolino** [comment]
Hey @Iansus 

I think you're using the wrong version. `impacket 0.9.19` (I think that's the version you're using, based on the error shown) does not support Python 3.x.

You should checkout master if you want to play with that feature.

**Comment by Iansus** [comment]
Do you have an estimate for a Python3 compatible pip package?

Thanks in advance,
Best regards

**Comment by asolino** [comment]
Not yet @Iansus, wanna wait for more feedback.

You can use the master version in the meantime.

**Comment by m1coco** [comment]
Hope to support 3.7

**Comment by cclauss** [comment]
Python 3.8 is on its last beta release so there is more pressure to test on that too.
https://discuss.python.org/t/action-required-python-3-8-0b4-available-for-testing/2231

**Comment by nh13inh** [comment]
It's no work on python 3x. These bunch of code still use python2.7 syntax

impacket/impacket/ImpactPacket.py 

class PacketBuffer(object):
    """Implement the basic operations utilized to operate on a
    packet's raw buffer. All the packet classes derive from this one.
    The byte, word, long and ip_address getters and setters accept
    negative indexes, having these the a similar effect as in a
    regular Python sequence slice.
    """

    def __init__(self, length = None):
        "If 'length' is specified the buffer is created with an initial size"
        if length:
            self.__bytes = array.array('B', b'\0' * length)
        else:
            self.__bytes = array.array('B')

    def set_bytes_from_string(self, data):
        "Sets the value of the packet buffer from the string 'data'"
        self.__bytes = array.array('B', data)

    def get_buffer_as_string(self):
        "Returns the packet buffer as a string object"
        return self.__bytes.tostring()

**Comment by cclauss** [comment]
Python 3.5 goes EOL on Sunday...  Might be time to shift up.

See #946 for some of the changes required for Python 3.9 release candidate 1.

**Comment by nh13inh** [comment]
Sorry, my pc used an old version of python3x. I didnt check it with newer version of Python3
Thank you for clarify it.

**Comment by nh13inh** [comment]
> Python 3.5 goes EOL on Sunday... Might be time to shift up.
> 
> Why claim that the above lines are Python 2 syntax? The work perfectly on Python 3.
> 
> See #946 for some of the changes required for Python 3.9 release candidate 1.


I just checked with python3.8. The same error with python3.5,  The version is not the issue here.
In python3 dont have the syntax "array.array('B', buffer)" anymore. I encounter this error when testing the lastest ver of impacket
TypeError: cannot use a str to initialize an array with typecode 'B'

**Comment by cclauss** [comment]
`str.encode("utf-8")` and `bytes.decode("utf-8")` are the opposite operation of each other.
So `array.array('B', my_bytes)` and `array.array('B', my_str.encode("utf-8"))` should be roughly equivalent.

**Comment by nh13inh** [comment]
> So `array.array('B', my_bytes)` and `array.array('B', my_str.encode("utf-8"))` should be roughly equivalent.

Thank you, I understand now. I need to covert the params to binary format. before that it was str format.
